// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Weatherman.Data;

namespace Weatherman.Data.Migrations
{
    [DbContext(typeof(WeathermanDbContext))]
    [Migration("20190725090632_weathermandbcontext.release.1")]
    partial class weathermandbcontextrelease1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Weatherman.Data.Models.ServerProfile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("LastChangedBy")
                        .HasColumnName("last_changed_by");

                    b.Property<DateTime?>("LastChangedDate")
                        .HasColumnName("last_changed_date");

                    b.Property<string>("Prefix")
                        .HasColumnName("prefix");

                    b.HasKey("Id")
                        .HasName("p_k_server_profile");

                    b.ToTable("server_profile");
                });

            modelBuilder.Entity("Weatherman.Data.Models.UserProfile", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<string>("HomeLocation")
                        .HasColumnName("home_location");

                    b.Property<DateTime?>("HomeLocationChangedDate")
                        .HasColumnName("home_location_changed_date");

                    b.Property<string>("LastLocation")
                        .HasColumnName("last_location");

                    b.Property<DateTime?>("LastLocationChangedDate")
                        .HasColumnName("last_location_changed_date");

                    b.HasKey("Id")
                        .HasName("p_k_user_profile");

                    b.ToTable("user_profile");
                });
#pragma warning restore 612, 618
        }
    }
}
